sudo: required
services:
  - docker

env:
  global:
    - IMAGE_NAME=dl-framework

before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile

install:
   - docker build -t ${IMAGE_NAME}:${TRAVIS_COMMIT} --pull=true .

script:
  - docker run ${IMAGE_NAME}:${TRAVIS_COMMIT} make test
